# Generated by Django 2.2.7 on 2019-12-03 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CostoEntrada', models.PositiveIntegerField()),
                ('entrada', models.CharField(choices=[('S', 'Standard'), ('V', 'VIP')], default='S', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Escenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreEscenario', models.CharField(max_length=35)),
                ('techado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1)),
                ('zona', models.CharField(choices=[('N', 'Norte'), ('S', 'Sur'), ('E', 'Este'), ('O', 'Oeste')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArtista', models.CharField(max_length=35)),
                ('dni', models.CharField(max_length=12)),
                ('generoMusical', models.CharField(max_length=35)),
                ('fechaPresentacion', models.DateField()),
                ('emailContacto', models.EmailField(max_length=254)),
                ('Escenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEntradas.Escenario')),
            ],
        ),
    ]
