# Generated by Django 2.2.7 on 2019-12-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEntradas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='descripcion',
            field=models.CharField(default=True, max_length=800, null=True),
        ),
    ]
