# Generated by Django 2.2.7 on 2019-12-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEntradas', '0002_artista_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=800),
        ),
    ]
